// Generated by CoffeeScript 1.4.0
(function() {
  var MONGO_URL, MYSQL_URL, PORT, REDIS_URL, SECRET, app, config, express, mongo, mongo_config, mongo_db, mysql, mysql_db, redis, redis_config, redis_db, routes, settings, url;

  url = require('url');

  express = require('express');

  mysql = require('mysql');

  redis = require('redis');

  mongo = require('mongodb');

  routes = require('./config/routes');

  config = require('./config/app');

  PORT = process.env.PORT || 8888;

  SECRET = process.env.SECRET || console.warn('Please Set Application Secret');

  MYSQL_URL = process.env.MYSQL_URL || console.warn('Please Set MySQL URL');

  REDIS_URL = process.env.REDIS_URL || console.warn('Please Set Redis URL');

  MONGO_URL = process.env.MONGO_URL || console.warn('Please Set Mongo URL');

  app = express();

  redis_config = url.parse(REDIS_URL);

  mongo_config = url.parse(MONGO_URL);

  mysql_db = mysql.createConnection(MYSQL_URL);

  redis_db = redis.createClient(redis_config.port, redis_config.hostname);

  mongo_db = new mongo.Server(mongo_config.hostname, mongo_config.port);

  redis_db.on('error', function() {
    return console.warn('Redis Reconnecting');
  });

  redis_db.on('connect', function() {
    return console.warn('Redis Connected');
  });

  settings = {
    secret: SECRET,
    "public": __dirname + '/public',
    views: __dirname + '/app/views'
  };

  config(app, settings);

  routes(app);

  app.listen(PORT);

  console.log('Server Listening on Port %d', PORT);

}).call(this);
